# Generated by Django 4.2.4 on 2023-10-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_genre_remove_movie_genres_movie_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
    ]
