# Generated by Django 4.2.4 on 2023-10-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watch_list',
            field=models.BooleanField(default=True),
        ),
    ]
