# Generated by Django 4.2.4 on 2023-10-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_movie_watch_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='backdrop_image',
            field=models.ImageField(blank=True, null=True, upload_to='movie_backdrops/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='movie_posters/'),
        ),
    ]
